//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PipeVolumeCalcService")]
    public partial class User : object
    {
        
        private string LoginField;
        
        private string PasswordField;
        
        private string _loginField;
        
        private string _passwordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _login
        {
            get
            {
                return this._loginField;
            }
            set
            {
                this._loginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _password
        {
            get
            {
                return this._passwordField;
            }
            set
            {
                this._passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CompositeType : object
    {
        
        private double ParamValueLField;
        
        private double ParamValueSField;
        
        private double ParamValueVField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ParamValueL
        {
            get
            {
                return this.ParamValueLField;
            }
            set
            {
                this.ParamValueLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ParamValueS
        {
            get
            {
                return this.ParamValueSField;
            }
            set
            {
                this.ParamValueSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ParamValueV
        {
            get
            {
                return this.ParamValueVField;
            }
            set
            {
                this.ParamValueVField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPipeVolumeCalculator")]
    public interface IPipeVolumeCalculator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipeVolumeCalculator/CalculatePipeVolume", ReplyAction="http://tempuri.org/IPipeVolumeCalculator/CalculatePipeVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IPipeVolumeCalculator/CalculatePipeVolumeArgumentExceptionFaul" +
            "t", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        System.Threading.Tasks.Task<double> CalculatePipeVolumeAsync(double L, double S);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipeVolumeCalculator/Authorize", ReplyAction="http://tempuri.org/IPipeVolumeCalculator/AuthorizeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IPipeVolumeCalculator/AuthorizeFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<bool> AuthorizeAsync(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipeVolumeCalculator/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPipeVolumeCalculator/GetDataUsingDataContractResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IPipeVolumeCalculator/GetDataUsingDataContractFaultExceptionFa" +
            "ult", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        System.Threading.Tasks.Task<ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPipeVolumeCalculatorChannel : ServiceReference1.IPipeVolumeCalculator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PipeVolumeCalculatorClient : System.ServiceModel.ClientBase<ServiceReference1.IPipeVolumeCalculator>, ServiceReference1.IPipeVolumeCalculator
    {
        
        public PipeVolumeCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> CalculatePipeVolumeAsync(double L, double S)
        {
            return base.Channel.CalculatePipeVolumeAsync(L, S);
        }
        
        public System.Threading.Tasks.Task<bool> AuthorizeAsync(ServiceReference1.User user)
        {
            return base.Channel.AuthorizeAsync(user);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ServiceReference1.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
